# Generated by Django 2.0.5 on 2018-05-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
