# Generated by Django 2.0.5 on 2018-06-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20180605_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=int, editable=False, primary_key=True, serialize=False),
        ),
    ]
